# MCP Manager Configuration Example
# Copy this file to ~/.config/mcp-manager/config.toml and customize

[logging]
# Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
level = "INFO"

# Log format: "text" or "json"
format_type = "text"

# Log file path (optional, relative to config_dir if not absolute)
file = "logs/app.log"

# Enable Rich console output
enable_rich = true

# Maximum log file size before rotation (bytes)
max_bytes = 10485760  # 10MB

# Number of backup files to keep
backup_count = 5

[claude]
# Path to Claude CLI executable
cli_path = "claude"

# Path to Claude MCP configuration file
config_path = "~/.config/claude-code/mcp-servers.json"

# Command timeout in seconds
timeout = 30

[discovery]
# NPM registry URL for server discovery
npm_registry = "https://registry.npmjs.org"

# Docker registry URL for server discovery
docker_registry = "docker.io"

# Cache TTL for discovery results (seconds)
cache_ttl = 3600

# Maximum number of search results
max_results = 100

[ui]
# UI theme: "dark" or "light"
theme = "dark"

# Enable animations in TUI
animations = true

# Confirm destructive operations
confirm_destructive = true

# Auto-refresh interval for TUI (seconds)
auto_refresh = 5